
matrix:"homeserver","HOMESERVER"
matrix:"user","USERID"
matrix:"pass","PASSWORD"

# PVA userid for Matrix
matrix:"id","@USERID:HOMESERVER"

# the adminid is the only one who can use this bot with the correct keyword OR "%" for free access 
matrix:"adminid","@ADMINID:HOMESERVER"

# Whats the name of your bot?
matrix:"device","NAME"

# initial room to join
matrix:"joinroom","!MATRIX_ROOMID"

# Incase of a server fail, additional alerts go here. Leave empty if you do not need it
matrix:"alertroom","!MATRIX_ROOMID"

# Simple 5 Secondtimeouted Connects() 
serverwatch:"hosts","servername:port,servername2:port,.."
serverwatch:"interval","60000"


command:"liste|matrix|räume|auf","MATRIX_LISTROOMS","",""
command:"liste|matrixräume|auf","MATRIX_LISTROOMS","",""

