#!/bin/bash

if [ "$GTTS" == "1" ]; then

        GTTSBIN=$(which gtts-cli)

        if [ "$GTTSBIN" != "" ]; then

                if [ "$VOICE" == "" ]; then
                        VOICE="de";
                fi

                HASH=$(echo "$VOICE$1"| sha256sum | sed -e "s/ .*$//g")

                FILENAME="$HOME/.cache/pva/audio/$HASH.mp3"

                if [ ! -e $FILENAME ]; then
                        echo "download from G -> \"$1\" -> $FILENAME"
                        gtts-cli "$1" --tld de --lang $VOICE --output $FILENAME
                fi

                play $FILENAME tempo 1.5 2>/dev/null

                exit;
        fi

        # GTTS is not here, continue with mbrola, if available
fi

# Check for mbrola


MBROLAINSTALLED=$(which mbrola)


if [ "$MBROLAINSTALLED" == "" ]; then 

	# REVERTING to espeak, because mbrola is missing

	if [ "$VOICE" == "" ]; then
        	VOICE="de"
	fi


	if [ ! -f "$1" ]; then

		espeak -v $VOICE "$1"

	else 
		cat "$1" | espeak -v $VOICE 

	fi
	exit;
fi 

if [ "$VOICE" == "" ]; then
	VOICE="de"
fi

if [ "$VOICE" == "de" ]; then
	VOICE="de5"
else 
	VOICE="$VOICE1"
fi

FILENAME=/tmp/mbrola$RANDOM.wav
PHONAME=/tmp/out.pho.$RANDOM

if [ ! -f "$1" ]; then
	espeak -v mb-$VOICE -q --pho --phonout=$PHONAME "$1"
else 
	cat "$1" | espeak -v mb-$VOICE -q --pho --phonout=$PHONAME
fi

mbrola -t 1.2 -f 0.8 /usr/share/mbrola/$VOICE/$VOICE $PHONAME $FILENAME
aplay $FILENAME 1>/dev/null 2>/dev/null

rm -f $FILENAME
rm -f $PHONAME
