#!/bin/bash


if [ "$GTTS" == "1" ]; then

	HASH=$(echo "$1"| sha256sum | sed -e "s/ .*$//g")

	FILENAME="$HOME/.cache/pva/audio/$HASH.mp3"

	if [ ! -e $FILENAME ]; then
		echo "download from G"
		gtts-cli "$1" --tld de --lang de --output $FILENAME 
	fi 

	play $FILENAME tempo 1.5 2>/dev/null

	exit;
fi

# Check for mbrola

MBROLAINSTALLED=$(which mbrola)


if [ "$MBROLAINSTALLED" == "" ]; then 

	# REVERTING to espeak, because mbrola is missing

	if [ "$VOICE" == "" ]; then
        	VOICE="de"
	fi


	if [ ! -f "$1" ]; then

		espeak -v $VOICE "$1"

	else 
		cat "$1" | espeak -v $VOICE 

	fi
	exit;
fi 

if [ "$VOICE" == "" ]; then
	VOICE="de5"
fi

FILENAME=/tmp/mbrola$RANDOM.wav

if [ ! -f "$1" ]; then
	espeak -v mb-$VOICE -q --pho --phonout=/tmp/out.pho "$1"
else 
	cat "$1" | espeak -v mb-$VOICE -q --pho --phonout=/tmp/out.pho 
fi

mbrola -t 1.2 -f 0.8 /usr/share/mbrola/$VOICE/$VOICE /tmp/out.pho $FILENAME
aplay $FILENAME 1>/dev/null 2>/dev/null

rm -f /tmp/mbrola*wav
rm -f /tmp/out.pho
