
# Default settings vor serverwatch plugin

serverwatch:"hosts","hostname:port,hostname1:port1"
serverwatch:"interval","60000"
serverwatch:"mailbox","imapmailboxID for SMTP"
serverwatch:"sendalarmfrom","alert@hostname.tld"
serverwatch:"adminmail","e@mail.tld"

# Hint: 

# matrix:"joinroom","!ROOMID"
# matrix:"alertroom","!ROOMID"

# are also used to send alerts via Matrix.
