#!/bin/bash

# Download and install https://github.com/reorx/ai.py
# go to open.ai, register an account, create an api key, follow instructions to add the key to your local ai.py conf
# enable chatgpt in your local copy of 12-chatgpt.conf


if [ ! -e "$HOME/.cache/pva/history.json" ]; then

	# create empty file 
	echo "[]" > $HOME/.cache/pva/history.json
	
fi 

echo "$(/usr/local/sbin/ai.py --history $HOME/.cache/pva/history.json -w -c "$1" 2>/dev/null </dev/null)"
