#!/bin/bash

# Support for Linux am Dienstag RECALL Plugin
# https://github.com/Cyborgscode/Linux-Recall-in-bash


CONFIG=$HOME/.config/recall/config

source $CONFIG

if [ "$STORAGELOCATION" == "" ]; then 
	exit 1;
fi 

SUCHE=$1

TREFFER=$(grep -l -i "$SUCHE" $STORAGELOCATION/*txt| sed -e "s/\.txt$//g")

# Eye of Gnome is a GNOME Imageviewer

eog -n -w -s $TREFFER
