#!/bin/bash

# Support for Linux am Dienstag RECALL Plugin
# https://github.com/Cyborgscode/Linux-Recall-in-bash

BILDER=$(cat $HOME/.config/recall/path)

if [ "$BILDER" == "" ]; then 
	exit 1;
fi 

SUCHE=$1

TREFFER=$(grep -l -i "$SUCHE" $BILDER/*txt| sed -e "s/\.txt$//g")

# Eye of Gnome is a GNOME Imageviewer

eog -n -w -s $TREFFER
